name: Update the PyPI chart badge

on:
  schedule:
    # Runs the first day of every month
    # Check out https://crontab.guru/#*_*_1_*_*
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update-chart-badge:
    name: Updating the pypi chart badge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Updating the badge
        uses: lnxpy/pypi-chart-badge@v1.4
        with:
          package_name: apyrat
          badge_color: black
          badge_dark_color: white

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chart badge updated"