name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: requirements_dev.txt
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: pip install -r requirements_dev.txt
      - name: Static code analysis
        run: make lint
      - name: Python unit tests
        run: make test
